<a href="https://colab.research.google.com/github/Astraplas/LinearAlgebra_2ndSem/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE
## Laboratory 4: Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

## Objectives
At the end of this activity you will be able to: 
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations. 
3. Program and translate matrix equations and operations using Python.

# Discussion

The following codes below will serve as a foundation in doing several codes that involves the use of matrix in Python itself.

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.


Let's say for example $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        2x + 3y \\ 
        46x - 150y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        3x+7y+9z \\ 
        8x -5y -3z \\
        2x + 5y +3z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
        5w-4x+7y+41z \\ 
        33w -5x -21y +6z \\
        22w -5x + 33y -22z
    \end{array}
\right. $$


We could see that $A$ is a system of equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 2 & 3 \\ 46 & {-150}\end{bmatrix} \\
B=\begin{bmatrix} 3 & 7 & 9 \\ 8 & -5 & -3 \\ 2 & 5 & 3\end{bmatrix} \\
C=\begin{bmatrix} 5 & -4 & 7 & 41 \\ 32 & -5 & -21 & 6 \\ 22 & -5 & 33 & -22\end{bmatrix}
$$



So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

## Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be represented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


We have already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using **shape**, **dimensions**, and **size** attributes, we'll use them to analyze these matrices

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

I think I can use this in future programs that is related to matrices.

In [ ]:
## Declaring a 2 x 2 Matrix 
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



The dimension of the matrix above is (2x2) and has been described accurately by the displayed output.

In [ ]:
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)

Matrix:
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In here, the rank is 2 and the dimension of the matrix above is (2x3) and has been described as it is in the output displayed.

In [ ]:
## Declaring a 3 x 2 Matrix
B = np.array([
    [8,2],
    [5,4],
    [1,1]
])
describe_mat(B)


Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In here, shape of the matrix is (3, 2) meaning, it has a dimension of (3x2) and a rank of 2 just like the displayed output.

In [ ]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



Lastly, the rank of this particular matrix is only 1 and is corresponding dimensions is (1x5).

As could be seen in the declared matrices above, their shape, size, and rank were displayed as an output.

## Categorizing Matrices

There are several ways of classifying matrices.Once could be according to their **shape** and another is according to their **element values**. We'll try to go through them.

### According to Shapes

Row an column are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)                       

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In the code above, two matrices were made. the first one has a dimension of (1x3) and the second one has a dimension of (1x4).

In [ ]:
## Declaring a Column Matrix

col_mat = np.array ([
    [15],
    [52],
    [576]                
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[ 15]
 [ 52]
 [576]]

Shape:	(3, 1)
Rank:	2



In here, the rank is 2 and the dimension of the matrix above is (3x1) and has been described as it is in the output displayed.

### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor funtion to determine square matrices.

In [ ]:
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\
  nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
     [1,2,5],
     [3,3,8],
     [6,1,2]                  
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2  nIs Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2  nIs Square: False



In the code above, the first matrix is square since the row and columns are the same in magnitude. However, for the second matrix, it is not a square since the row and column are not equivalent.

### According to Element Values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
  if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False
      print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
      print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


The code above has become a null matrix since there are no value enter in the matrix itself.

#### Zero Matrix

A zero matrix can ba any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In here, the shape were the input, and the program would make the value of all the given shape to be zero. Therefore, making the matrix a zero matrix.

#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


The same process for the zero matrix was repeated, but in here, instead of making all of the values for the given shape to be zero it will instead make the values to be all one. Thus, making the matrix a ones matrix.

#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
np.array([
      [2,0,0],
      [0,3,0],
      [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1, n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

Since the given matrix is a square matrix, and all of the values are only in the diagonal of the square matrix. It is then a diagonal matrix.

In [ ]:
d = np.diag([2,3,5,7])
d.shape[0] == d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In contrast to the first created diagonal matrix. In here, in np.diag was used and all of the entered values was entered diagonally.

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.


In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

There are not much of a difference to identity and diagonal matrix. It's just that in identity matrix, instead of random values, it will be instead values of 1 in the diagonal.

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Compared to the first created matrix which used np.eye, in here it used np.identity in order to create an identity matrix.

#### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal. 

In [ ]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In here, it is a variation of the diagonal matrix in which only the diagonal and its upper side only contains any value.

#### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

Similar to the upper triangular matrix, in the lower triangular matrix instead of the upper side, it would now have its values on the diagonal and the lower side of the diagonal. Therefore, making it a lower triangular matrix.

### Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.


$$\theta = 5x + 3y - z$$



$$
\theta = \begin{bmatrix} 5 & 3 & -1\end{bmatrix} \\
$$

2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


$$
A = \begin{bmatrix} 1 & 2 & 1 \\ 0 & 4 & -1 \\ 0 & 0 & 10\end{bmatrix} \\
$$

The matrix is square, with a rank of 2. It has a shape of (3, 3). It is also an upper triangular matrix.

In [1]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs square: {is_square}\n')

In [6]:
A = np.array([
   [1,2,1],
   [0,4,-1],
   [0,0,10]                     
])

describe_mat(A)

Matrix:
[[ 1  2  1]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is square: True



3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])


$$
G = \left\{\begin{array}
1x_1 + 7x_2 +8x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

$$
G = \left\{\begin{array}
5x_1 + 7x_2 + 8x_3\\
2x_1 + 2x_2 + 2x_3\\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

$$
G = \begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}
$$



```
# This is formatted as code
```

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

$$
A = \left\{\begin{array}
5x_1 \\
2x_1 + 2x_2 \\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

$$
H = \begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7\end{bmatrix}
$$

$$
H = \left\{\begin{array}
5x_1 \\
2x_1 + 2x_2 \\
4x_1 + 6x_2 + 7x_3
\end{array}\right.
$$

## Matrix Algebra

#### Addition

In [ ]:
A = np.array([
      [1,2],
      [2,3],
      [4,1]
])
B = np.array([
      [2,2],
      [0,0],
      [1,1]       
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In here, the values for the A and B matrix was first entered and then an addition of matrix has taken place.

In [ ]:
2+A ##Broadcasting 
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

The matrix A had all of its values added by 2 and the output was displayed.

#### Subtraction

In [ ]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In this matrix, the matrix A was subtracted by the values in the matrix B. Since their dimensions are the same, the subtraction of matrix has taken place without an error.

In [ ]:
3-B

array([[1, 1],
       [3, 3],
       [2, 2]])

In here, it is simply the values of the matrix B is subtracted to 3.

In [ ]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

For here, the output made was regarding the values are true or false. Hereby, displaying true for all of the values.

#### Element-wise Multiplication

In [ ]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

The given A matrix and B matrix was multiplied in here and its corresponding output was displayed.

In [ ]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In here, the given Matrix A was simply multiplied to 2, thus making all of the values of A become doubled.

In [ ]:
alpha = 10**-10
A/((alpha+B))

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

The values inputted in here was raised to the power of -10, and its resulting output was displayed.

## Activity

### Task 1

**Create** a function named `mat_desc()` that througouhly describes a matrix, it should: <br>
1. Displays the shape, size, and rank of the matrix. <br>
2. Displays whether the matrix is square or non-square. <br>
3. Displays whether the matrix is an empty matrix. <br>
4. Displays if the matrix is an identity, ones, or zeros matrix <br>
   
Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline
X = int(input("Number of rows:"))
Y = int(input("Number of columns:")) 
print("Entries per row (separated by space): ")  
entries = list(map(int, input().split()))
num_entries = len(entries)
area_dim = X*Y
##validation if the number of entry is not inclined in the product of row and column.
if (area_dim != num_entries):
  print("Invalid input of entry. Your number of entries must be equal to the product of row and column.")
  raise ValueError("Error! Please enter the correct number of series in entry.")
matrix = np.array(entries).reshape(X, Y)
def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'\nMatrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}')
describe_mat(matrix)
is_empty = matrix == 0
if False:
  print('The matrix is empty')
else:
   print('The matrix is not empty')
point=0
for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        if i == j and matrix[i][j] != 1:
            point=1 
            break
        elif i!=j and matrix[i][j]!=0:
            point=1
            break
if point==1:
    print("The matrix is not an identity matrix.")
else:
    print("The matrix is an identity matrix.")
arr = matrix
is_all_zero = np.all((arr == 0))
if is_all_zero:
    print('The matrix only have 0')
else:
    print('The matrix has non-zero items')
arr = matrix
is_all_zero = np.all((arr == 1))
if is_all_zero:
    print('The matrix only have 1')
else:
    print('The matrix non-ones items')

Number of rows:3
Number of columns:3
Entries per row (separated by space): 
1 0 0 0 1 0 0 0 1

Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Shape:	(3, 3)
Rank:	2
Is Square: True
The matrix is not empty
The matrix is an identity matrix.
The matrix has non-zero items
The matrix non-ones items


In [ ]:
## Function area

In [ ]:
## Matrix declarations

In [ ]:
## Test Areas

### Task 2

Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 3 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline
X = int(input("Number of rows for 1st Matrix: "))
Y = int(input("Number of columns for 1st Matrix: ")) 
print("Entries per row (separated by space): ")  
entries_1 = list(map(int, input().split()))
 
num_entries_1 = len(entries_1)
area_dim_1 = X*Y

def describe_mat(matrix):
  is_square = True if matrix.shape[0] == matrix.shape[1] else False
  print(f'\nMatrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n\n')

##validation if the number of entry is not inclined in the product of row and column.
if (area_dim_1 != num_entries_1):
  print("Invalid input of entry. Your number of entries must be equal to the product of row and column.")
  raise ValueError("Error! Please enter the correct number of series in entry.")

matrix_1 = np.array(entries_1).reshape(X, Y)

describe_mat (matrix_1)
###############################################################################################################
A = int(input("Number of rows for 2nd Matrix: "))
B = int(input("Number of colums for 2nd Matrix: "))
print("Entries per row (separated by space): ")
entries_2 = list(map(int, input().split()))

num_entries_2 = len(entries_2)
area_dim_2 = A*B

##validation if the number of entry is not inclined in the product of row and column.
if (area_dim_2 != num_entries_2):
  print("Invalid input of entry. Your number of entries must be equal to the product of row and column.")
  raise ValueError("Error! Please enter the correct number of series in entry.")

matrix_2 = np.array(entries_2).reshape(A, B)
describe_mat (matrix_2)
#################################################################################################################
dec_operation = input ("Enter Your Desired Operation (+,-,*,/) : ")
####################################ADDITION######################################################################
if dec_operation == '+' or dec_operation.lower() == "addition": 
  Matrix_sum = matrix_1 + matrix_2
  print("The Sum of the two Matrices are: \n{}".format(Matrix_sum))
####################################SUBTRACTION###################################################################
if dec_operation == '-' or dec_operation.lower() == "subtraction": 
  Matrix_diff = matrix_1 - matrix_2
  print("The Difference of the two Matrices are: \n{}".format(Matrix_diff))
####################################MULTIPLICATION################################################################
if dec_operation == '*' or dec_operation.lower() == "multiplication": 
  Matrix_prod = matrix_1 * matrix_2
  print("The Product of the two Matrices are: \n{}".format(Matrix_prod))
#####################################DIVISION#####################################################################
if dec_operation == '/' or dec_operation.lower() == "division": 
  Matrix_quo = matrix_1 / matrix_2
  print("The Quotient of the two Matrices are: \n{}".format(Matrix_quo))
##################################################################################################################

Number of rows for 1st Matrix: 3
Number of columns for 1st Matrix: 3
Entries per row (separated by space): 
1 4 5 6 7 8 3 4 6

Matrix:
[[1 4 5]
 [6 7 8]
 [3 4 6]]

Shape:	(3, 3)
Rank:	2
Is Square: True


Number of rows for 2nd Matrix: 3
Number of colums for 2nd Matrix: 3
Entries per row (separated by space): 
3 5 2 6 7 5 2 4 1

Matrix:
[[3 5 2]
 [6 7 5]
 [2 4 1]]

Shape:	(3, 3)
Rank:	2
Is Square: True


Enter Your Desired Operation (+,-,*,/) : *
The Product of the two Matrices are: 
[[ 3 20 10]
 [36 49 40]
 [ 6 16  6]]


## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "How can matrix operations solve problems in technology?".

(Conclusion from the Lab Report)

The basic knowledge about declaring matrices, classifying matrices, and matrix algebra has been understood by the students. The students demonstrated the understanding that they have by creating two programs that integrate the principle of matrix in Python. The first program determines the classification of the matrix, and the second program would apply the principles of matrix algebra As such, it will serve as a foundation in order for the students to create and execute a comparatively more complex program.


With all of this in mind, applying these concepts to the way how technology is being used, it will make calculations, approximation, and processing easier and faster. For instance, applying the principle of multiplication of matrices, it could aid in hastening the process of digital videos and sounds. Furthermore, matrices could also be used to create representations of wireless signals in order to increase their efficiency. Matrices themselves play a crucial role when it comes to estimating signals and detecting problems in signal. As such, it is a conclusive fact that matrices are involved in solving and alleviating the problems encountered when technologies are used.
